#!/usr/bin/env python3
"""Generate a self-contained M3DGR localization YAML from a map start pose."""

from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path

import numpy as np
import yaml


def parse_args() -> argparse.Namespace:
    repo = Path(__file__).resolve().parents[3]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--base", type=Path,
        default=repo / "config" / "reproduction" / "single_lidar" / "m3dgr"
        / "lightning_m3dgr_mid360_benchmark.yaml",
    )
    parser.add_argument("--map-index", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def read_start_pose(index_path: Path) -> tuple[list[float], list[float]]:
    functional = False
    for line_number, raw in enumerate(index_path.read_text(encoding="utf-8-sig").splitlines(), 1):
        line = raw.strip()
        if line == "# functional points":
            functional = True
            continue
        if not functional or not line:
            continue
        fields = line.split()
        if fields[0] != "start":
            continue
        if len(fields) != 8:
            raise ValueError(f"{index_path}:{line_number}: invalid start functional point")
        values = np.asarray([float(value) for value in fields[1:]], dtype=np.float64)
        if not np.all(np.isfinite(values)) or abs(np.linalg.norm(values[3:]) - 1.0) > 1e-3:
            raise ValueError(f"{index_path}:{line_number}: invalid start pose")
        values[3:] /= np.linalg.norm(values[3:])
        return values[:3].tolist(), values[3:].tolist()
    raise ValueError(f"start functional point not found: {index_path}")


def main() -> int:
    args = parse_args()
    if not args.base.is_file() or not args.map_index.is_file():
        raise SystemExit("base YAML and map index must exist")
    config = yaml.safe_load(args.base.read_text(encoding="utf-8"))
    if not isinstance(config, dict):
        raise SystemExit(f"invalid base YAML: {args.base}")
    translation, quaternion = read_start_pose(args.map_index)

    config.setdefault("system", {})["with_loop_closing"] = False
    config.setdefault("backend", {})["mode"] = "disabled"
    config["localization_pgo"] = {
        "enable_dr_extrapolation": True,
        "enable_dr_smoothing": True,
    }
    config["lidar_loc"] = {
        "enable_dynamic_polygon": False,
        "enable_parking_static": False,
        "enable_icp_adjust": False,
        "filter_intensity_max": 100.0,
        "filter_intensity_min": 0.0,
        "filter_z_max": 100.0,
        "filter_z_min": -100.0,
        "force_2d": False,
        "grid_search_angle_range": 20.0,
        "grid_search_angle_step": 20.0,
        "lidar_loc_odom_th": 1.0,
        "init_with_fp": False,
        "min_init_confidence": 0.5,
        "min_tracking_confidence": 0.4,
        "update_dynamic_cloud": False,
        "update_err_h": 0.2,
        "update_err_v": 0.2,
        "update_kf_dis": 2.0,
        "update_lidar_loc_score": 2.5,
        "loc_on_kf": False,
        "try_self_extrap": False,
    }
    config["relocalization"] = {
        "enabled": False,
        "database_subdirectory": "btc_relocalization",
        "lost_frame_threshold": 5,
        "enable_map_consistency": False,
    }
    config["maps"] = {
        "delete_when_unload": False,
        "dyn_cloud_policy": "persistent",
        "load_dyn_cloud": False,
        "load_map_size": 2,
        "max_pts_dyn_chunk": 100000,
        "save_dyn_when_quit": False,
        "save_dyn_when_unload": False,
        "unload_map_size": 4,
        "with_dyn_area": False,
    }
    config["offline_localization"] = {
        "initial_pose": {
            "enabled": True,
            "translation": translation,
            "quaternion_xyzw": quaternion,
        }
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    temporary = args.output.with_suffix(args.output.suffix + ".tmp")
    with temporary.open("w", encoding="utf-8") as stream:
        stream.write("# Generated by prepare_m3dgr_localization_config.py\n")
        stream.write(f"# base_sha256: {sha256(args.base)}\n")
        stream.write(f"# map_index_sha256: {sha256(args.map_index)}\n")
        yaml.safe_dump(config, stream, allow_unicode=True, sort_keys=False, default_flow_style=False)
    os.replace(temporary, args.output)
    print(args.output.resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
