#!/usr/bin/env python3
"""Generate frozen single-114 and four-LiDAR SANY mapping configs."""

from __future__ import annotations

import argparse
import copy
from pathlib import Path

import yaml


def main() -> int:
    repo = Path(__file__).resolve().parents[3]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--base", type=Path,
        default=repo / "config" / "reproduction" / "multi_lidar" / "sany_4livox"
        / "sany_4lidar_frontend_final.yaml",
    )
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()
    base = yaml.safe_load(args.base.read_text(encoding="utf-8"))
    if not isinstance(base, dict) or "multi_lidar" not in base or "backend" not in base:
        raise SystemExit(f"invalid SANY base config: {args.base}")
    specifications = {
        "single114": {"multi_enabled": False, "noise_enabled": True, "drop_id": None},
        "four_lidar": {"multi_enabled": True, "noise_enabled": True, "drop_id": None},
        "four_no_noise": {"multi_enabled": True, "noise_enabled": False, "drop_id": None},
        "drop114": {"multi_enabled": True, "noise_enabled": True, "drop_id": 0},
        "drop127": {"multi_enabled": True, "noise_enabled": True, "drop_id": 1},
        "drop187": {"multi_enabled": True, "noise_enabled": True, "drop_id": 2},
        "drop195": {"multi_enabled": True, "noise_enabled": True, "drop_id": 3},
    }
    variants = {}
    for name, specification in specifications.items():
        config = copy.deepcopy(base)
        config["multi_lidar"]["enabled"] = specification["multi_enabled"]
        config["lidar_noise_model"]["enabled"] = specification["noise_enabled"]
        if specification["drop_id"] is not None:
            lidar_id = specification["drop_id"]
            config["multi_lidar"]["topics"][f"lidar_{lidar_id}"] = f"/fault_injection/missing_lidar_{lidar_id}"
        config.setdefault("common", {})["benchmark_variant"] = name
        config.setdefault("system", {})["with_loop_closing"] = True
        config.setdefault("backend", {})["mode"] = "ba_btc_hba"
        variants[name] = config
    args.output_dir.mkdir(parents=True, exist_ok=True)
    for name, config in variants.items():
        output = args.output_dir / f"sany_20260701_{name}.yaml"
        with output.open("w", encoding="utf-8") as stream:
            stream.write(f"# Generated by prepare_sany_mapping_configs.py; variant={name}\n")
            yaml.safe_dump(config, stream, allow_unicode=True, sort_keys=False, default_flow_style=False)
        print(output.resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
