#!/usr/bin/env python3
"""Freeze a SANY localization config for one global-relocalization backend."""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml


def main() -> int:
    repo = Path(__file__).resolve().parents[4]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--base",
        type=Path,
        default=repo
        / "config"
        / "reproduction"
        / "multi_lidar"
        / "sany_4livox"
        / "sany_4lidar_mapping.yaml",
    )
    parser.add_argument(
        "--backend",
        choices=("btc", "solid", "solid_kiss"),
        required=True,
    )
    parser.add_argument("--compute-backend", choices=("auto", "cpu", "gpu"), default="cpu")
    parser.add_argument("--debug-candidate-id", type=int, action="append", default=[])
    parser.add_argument("--top-k", type=int)
    parser.add_argument("--retrieval-pool-size", type=int)
    parser.add_argument("--icp-yaw-offset-deg", type=float, action="append")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    config = yaml.safe_load(args.base.read_text(encoding="utf-8"))
    relocalization = config.get("relocalization") if isinstance(config, dict) else None
    if not isinstance(relocalization, dict):
        raise SystemExit(f"missing relocalization section: {args.base}")
    solid = relocalization.get("solid")
    if not isinstance(solid, dict):
        raise SystemExit(f"missing relocalization.solid section: {args.base}")

    relocalization["backend"] = args.backend
    if args.backend in ("solid", "solid_kiss"):
        solid["compute_backend"] = args.compute_backend
    effective_solid = solid
    if args.backend == "solid_kiss":
        effective_solid = relocalization.get("solid_kiss")
        if not isinstance(effective_solid, dict):
            raise SystemExit(f"missing relocalization.solid_kiss section: {args.base}")
    # Online deployment owns all hotspot worker limits in one section. Keep
    # the legacy nested key out of newly frozen configs to avoid two sources
    # of truth; older configs remain supported by the C++ loader.
    solid.pop("icp_workers", None)
    compute_budget = config.setdefault("compute_budget", {})
    compute_budget.setdefault("lio_threads", 6)
    compute_budget.setdefault("ndt_threads", 4)
    compute_budget.setdefault("solid_icp_workers", 12)
    compute_budget.setdefault("solid_worker_nice", 5)
    solid["debug_candidate_ids"] = args.debug_candidate_id
    if args.top_k is not None:
        if args.top_k <= 0:
            raise SystemExit("--top-k must be positive")
        effective_solid["top_k"] = args.top_k
    if args.retrieval_pool_size is not None:
        if args.retrieval_pool_size < effective_solid["top_k"]:
            raise SystemExit("--retrieval-pool-size must be >= top_k")
        effective_solid["retrieval_pool_size"] = args.retrieval_pool_size
    if args.icp_yaw_offset_deg is not None:
        if args.backend == "solid_kiss":
            raise SystemExit("--icp-yaw-offset-deg is only valid for the solid backend")
        if not args.icp_yaw_offset_deg:
            raise SystemExit("at least one ICP yaw offset is required")
        solid["icp_yaw_hypothesis_offsets_deg"] = args.icp_yaw_offset_deg
    variant = f"relocalization_{args.backend}"
    if args.backend in ("solid", "solid_kiss"):
        variant += f"_{args.compute_backend}"
    config.setdefault("common", {})["benchmark_variant"] = variant

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as stream:
        stream.write(
            "# Generated by prepare_relocalization_config.py; "
            f"backend={args.backend}; compute_backend="
            f"{args.compute_backend if args.backend in ('solid', 'solid_kiss') else 'n/a'}\n"
        )
        stream.write(
            "# Frozen SANY localization configuration; sensor layout is inherited from --base.\n"
        )
        yaml.safe_dump(
            config,
            stream,
            allow_unicode=True,
            sort_keys=False,
            default_flow_style=False,
        )
    print(args.output.resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
